### PR TITLE
More updates to profile listings view

### PR DESCRIPTION
**Pull request by Braagaa**
**What it does:**

There is now a splash loader (circular animation) when there is data being fetched for full listings and individual profiles.
There is a Snackbar for full listings and individual profiles when there is any errors.
When there is no sitters found a simple "No Results Found" is displayed.
"Show more" button is gone during loading, errors, and no results found.
Created 2 utility components: a defaulted Snackbar componenet and a Splash loader components that can be used anywhere
Created utility hook useFetch for fetch api
Updated no results page

### CODE REVIEW

**Review by dproc96 — APPROVED** [review]
This looks good to me, only thing is I wanted to see if I could make your no results or error message come up by running the client without the server and I got this instead. I don't know if that's something that should've triggered your error messages or not:
Screen Shot 2020-10-24 at 3 48 27 PM

**Comment by Braagaa** [comment]
Thanks I'll look at it soon @dproc96

**Comment by Braagaa** [comment]
How did you replicate that? I got my Snackbar to show up when there was no connection to the server.

**Comment by dproc96** [comment]
> How did you replicate that? I got my Snackbar to show up when there was no connection to the server.

1. Be logged in with server running
2. Quite server process
3. Access Find A Sitter page

**Pull request merged**
