### PR TITLE
IN: Refactor how a sitter selects availability

### PR DESCRIPTION
**Pull request by dproc96**
**What it does**
- Create a new Calendar component
- Allows the sitter to set hour-long intervals between 8AM and 8PM for pickup and dropoff availability on a given day
- Allows the sitter to add the same times to multiple days with one click
- Alters styling to show the sitter what days have available times
- Converts from availability state to range format for Database and back

**What to look for**
- It's styled for desktop display, I'm not sure of the easiest way to alter it for mobile so some input would be very appreciated

Screen Shot 2020-11-01 at 2 56 47 PM

This gets us closer to our finished project by making it significantly easier for a sitter to add their availability

### CODE REVIEW

**Comment by Braagaa** [comment]
image

Hey @dproc96 I got this error

**Comment by dproc96** [comment]
> image
> 
> Hey @dproc96 I got this error

@Braagaa Looking at the code I'm betting that's because of old data (availability ranges that don't match the refactored format) regardless I've added some verification to prevent that error

Still you may need to drop and reseed your DB to test

**Comment by Braagaa** [comment]
> > image
> > Hey @dproc96 I got this error
> 
> @Braagaa Looking at the code I'm betting that's because of old data (availability ranges that don't match the refactored format) regardless I've added some verification to prevent that error
> 
> Still you may need to drop and reseed your DB to test

> Ya it works now

**Comment by Braagaa** [comment]
I get this now:

image

**Comment by Braagaa** [comment]
This looks awesome tho you put so much work, cant wait to try it.

**Comment by dproc96** [comment]
> I get this now:
> 
> image
> 

@Braagaa woops I put the conditionals in the wrong order, should be good now

**Comment by dproc96** [comment]
We should change how the seeding script generates availability because its causing a separate bug now that the error is resolved

**Review by dahrk — CHANGES_REQUESTED** [review]
Few bugs:
1. When you have a day selected and you change months, upon returning your selected date is the same but the indicator disappears
2. Adding availability on one day in a few non-continuous block for the same user shoots a 
PUT /profile/5fa0a5a04f9420a6d9a8c93e 500 20.509 ms - 518
InternalServerError: No matching document found for id "5fa0a5a04f9420a6d9a8c93e" version 0 modifiedPaths "availability, __v"
    at updateProfile (/home/td/code/hatchways/oct-coop/server/controllers/profile.js:86:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
3. A request, is it possible to show a grouped list of availabilities on the left side? It looks like the way the data is grouped by day in db, displaying these grouped by day would be great

**Comment by dproc96** [comment]
> Few bugs:
> 
> 1. When you have a day selected and you change months, upon returning your selected date is the same but the indicator disappears
> 2. Adding availability on one day in a few non-continuous block for the same user shoots a
>    PUT /profile/5fa0a5a04f9420a6d9a8c93e 500 20.509 ms - 518
>    InternalServerError: No matching document found for id "5fa0a5a04f9420a6d9a8c93e" version 0 modifiedPaths "availability, __v"
>    at updateProfile (/home/td/code/hatchways/oct-coop/server/controllers/profile.js:86:10)
>    at runMicrotasks ()
>    at processTicksAndRejections (node:internal/process/task_queues:93:5)
> 3. A request, is it possible to show a grouped list of availabilities on the left side? It looks like the way the data is grouped by day in db, displaying these grouped by day would be great

1. Fixed that, it should've nullified both when you move to a new month, it does now
2. That was due to me not updating the frontend profile to match the backend, creating a version error. I also added a progress bar that prevents sending two simultaneous requests
3. I have two possible solutions on the branch now one was suggested by @dahrk and that's the block listings and one suggested by @Braagaa which is showing the time blocks on hover. Which do you guys prefer?

**Review by dahrk — APPROVED** [review]
It's basically there. I'm willing to approve with a few tiny changes.

1. Selecting a day, switching months and switching back leaves the selected date in limbo still
2. There is an error regarding unique keys in the Calendar.js grid elements and Availability.js
3. I think I'm ok with both versions of displaying availability showing up. It works well and the person can use whatever is easier for them.

**Pull request merged**
