### PR TITLE
Feature filter listings

### PR DESCRIPTION
**Pull request by Braagaa**
**What it does**

- Searches and filters sitter profiles on find sitters on "Find a Sitter" page
- Searches firstName, lastName, location, rating, payranges, and date ranges
- Basic sorting for most categories
- Pagination

**What to look for**

- Uses URL queries to keep history of searches

**What to watch out for**

- Might want to reseed the database with the updated script to make sure it runs wells

### CODE REVIEW

**Review by dproc96 — CHANGES_REQUESTED** [review]
Just a couple of things I noticed:
- With no filters, I'm only seeing two options: myself and user1
Screen Shot 2020-11-01 at 3 19 00 PM

- When hitting close after applying a filter I would expect the filter to apply immediately but I have to hit search again

- The search bar looks a little odd overlayed on the background, maybe putting it in a card would help?

- The Hourly Rate option goes up to $300, I feel like that's pretty high for a sitter

- I'm not really sure what the use case for sort by availability is, I think being able to filter by it is enough

**Comment by Braagaa** [comment]
> Just a couple of things I noticed:
> 
> * With no filters, I'm only seeing two options: myself and user1
> 
> Screen Shot 2020-11-01 at 3 19 00 PM
> 
> * When hitting close after applying a filter I would expect the filter to apply immediately but I have to hit search again
> * The search bar looks a little odd overlayed on the background, maybe putting it in a card would help?
> * The Hourly Rate option goes up to $300, I feel like that's pretty high for a sitter
> * I'm not really sure what the use case for sort by availability is, I think being able to filter by it is enough

Hey those are some good suggestions that I went over. Take a look when you can.

**Review by dahrk — COMMENTED** [review]
The feature isn't working for me locally - my steps were pull and npm install in both client & server. Boot server and populate with script. Try and search. Any thoughts?

You'll also want to check your regex matching with "search", it is very strict and case sensitive

**Comment by Braagaa** [comment]
> The feature isn't working for me locally - my steps were pull and npm install in both client & server. Boot server and populate with script. Try and search. Any thoughts?
> 
> You'll also want to check your regex matching with "search", it is very strict and case sensitive

I just fixed it up, I used the script from another branch but I just tried it now and should be good. Just re run the seed script.

**Review by dahrk — CHANGES_REQUESTED** [review]
I still have some problems with searching:
1. Availability is not working properly for me - we can wait until the calendar fix is merged and use that format if you wish. Don't be afraid to do extra filtering inside the api route, functionality is more important than efficiency
2. Name search is still too strict, look into something like /.*search.*/ for your string so that "ara" can match "Tara" for example. Currently only exact matches to first or last name return a sitter

**Comment by dproc96** [comment]
Screen Shot 2020-11-04 at 8 25 23 PM
This is pretty minor, but you might want to see about making the numbers normalize to two decimals (I can't remember how but I think it's relatively easy)

Screen Shot 2020-11-04 at 8 27 17 PM
This threw me off while I was messing around with it, should it default to searching by name?


I also noticed that search by rating is only returning exact matches, do you think it's better to do that or return greater than or equal to (i.e. a 4 star sitter if you select 3 stars)?

Other than these minor questions, I think this looks great @Braagaa !

**Review by dproc96 — APPROVED** [review]
This looks good to me now!

**Pull request merged**
